### Get all todos
GET http://localhost:3000/api/todos
Content-Type: application/json


### Get a specific todo
GET http://localhost:3000/api/todos/1
Content-Type: application/json


### Create new todo
POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "title": "Learn React"
}


### Update a todo
PUT http://localhost:3000/api/todos/1
Content-Type: application/json

{
  "title": "Finish Express Project",
  "completed": true
}


### Delete a todo
DELETE http://localhost:3000/api/todos/1
Content-Type: application/json
